# ~/.config/i3/i3blocks.conf
# i3blocks configuration

# Global properties
full_text=
align=center
color=#0f1c21aa
background=#ffffff
separator=false
separator_block_width=7
markup=pango

[application]
command=~/.config/i3/scripts/application
color=#ffffff
background=#0f1c21aa
interval=1

[network]
command=~/.config/i3/scripts/network
interval=1
signal=11
markup=pango
color=#ffffff
background=#0f1c21aa

[cpu_usage]
command=~/.config/i3/scripts/cpu_usage
interval=1
color=#ffffff
background=#0f1c21aa

[disk]
command=~/.config/i3/scripts/disk
color=#ffffff
background=#0f1c21aa
interval=1

[volume]
command=~/.config/i3/scripts/volume
interval=1
signal=10
markup=pango
color=#ffffff
background=#0f1c21aa

[battery]
command=~/.config/i3/scripts/battery
color=#ffffff
background=#0f1c21aa
interval=5

[datetime]
command=~/.config/i3/scripts/datetime
color=#ffffff
background=#0f1c21aa
interval=1
